# -*- coding: utf-8 -*-
"""Copy of  lec 3 Assignment -  Introduction to Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bVOTo3Ptb5h5ZVpo7hmBmGMF9us4XZ9C

## <u>While doing this assignment only use those concepts which have been taught till now</u>

## <u>Problem 1</u>

You are given a sentence which reads <b>"Wikipedia is a free online encyclopedia, created and edited by volunteers around the world and hosted by the Wikimedia Foundation."</b>

Find the number of words in the given sentence.
"""

# Store the given sentence in a variablers around the world and hosted by the Wikimedia Foundation."
a="Wikipedia is a free online encyclopedia, created and edited by volunteers around the world and hosted by the Wikimedia Foundation"

# Calculate the total number of words in the sentence.  Hint : Use the count() method
a.count(" ")+1
b=a.count(" ")+1

# Print the variable num_of_words
print(b)

"""## <u>Problem 2 </u>

Write a Python code which takes a number and returns a corresponding string of hyphens. For example if the number is 3, it will return '---' , if the number is 5 it will return '-----'
"""

# Store the user input in a variable
c= input("enter a number")

# Create a string of equivalent number of hyphens. Hint : remember what happens when we multiply string by a number?
b="-"

# Print the string of hyphens
# string_of_hyphens
print(b*int(c))

"""## <u> Problem 3 </u>

A string can be called a safe bridge if it has no gaps in it i.e, no spaces. You are supposed to take an input from the user and print whether the string is a safe bridge or not.
"""

# Store the user input in a variable
a=input("enter the string")

# Return True if the bridge is safe and False if the bridge is not safe. Hint : Use the find() method
b = a.count(" ")

# Fill in the blanks
if b == 0:
  print("its safe")
else:
     print("not safe")

"""## <u>Problem 4</u>

Count the number of D's in a string inputted by the user. This will be <b>case insensitive</b>.
"""

# Store the user input in a variable
user= "Debris was scattered all over the yard in the denset region of Denmark"

# Store the count of letter D in the inputted string. Note this will be a case insensitive search
k=user.count("D")
print(k)
s=user.lower()
print(s)
f=s.count("d")
print(f)

# Fill in the blanks
print("The total occurrence of D in the user_string is",s)
print("The total occurrence of d in the user_string is",f)

"""## <u>Problem 5</u>

Check whether a given string is a palindrome. A palindrome is a word, number, phrase, or other sequence of characters which reads the same backward as forward, such as madam, racecar.
"""

# Store the user input in a variable
info="nitin"
reverse=info[ : : -1]
print(reverse)

# Print True if a string is a Palindrome else print false
if info==reverse:
  print("given is palimdrom")
else:
  print("not palimdrom")



